# -*- coding: utf-8 -*-
"""Ass1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VnJmqwLdt9etZZUTgCVQ_zJXjMgBz_eg
"""

import numpy as np

!pip install crypto

import hashlib
import time
start_t=time.time()
txt=input()
x=0

target="0x00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
z=str(txt)+str(x)
y=hashlib.sha256(b"z").hexdigest()
while str(y) > target:
  print("time taken is:" ,(time.time()-start_t))
  x=x+1
  z=str(txt)+str(x)
  y=hashlib.sha256(str.encode(z)).hexdigest()
  print(y)